// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */
import { APIRequest, HTTPMethod } from "./types";
import * as operations from "./gen-ts";

export class listPets implements APIRequest<operations.listPetsResponse> {
  response: operations.listPetsResponse;
  method = HTTPMethod["get"];
  path: string;
  params: operations.listPetsRequest;

  constructor(args: {
    params: operations.listPetsRequest;
    pathParameter?: operations.listPetsPathParameter;
  }) {
    const { params, pathParameter } = args;
    this.params = params;
    this.path = `/pets`;
  }
}

export class createPets implements APIRequest<operations.createPetsResponse> {
  response: operations.createPetsResponse;
  method = HTTPMethod["post"];
  path: string;
  params?: operations.createPetsRequest;

  constructor(args: {
    params?: operations.createPetsRequest;
    pathParameter?: operations.createPetsPathParameter;
  }) {
    const { params, pathParameter } = args;
    this.params = params;
    this.path = `/pets`;
  }
}

export class showPetById implements APIRequest<operations.showPetByIdResponse> {
  response: operations.showPetByIdResponse;
  method = HTTPMethod["get"];
  path: string;
  params?: operations.showPetByIdRequest;

  constructor(args: {
    params?: operations.showPetByIdRequest;
    pathParameter: operations.showPetByIdPathParameter;
  }) {
    const { params, pathParameter } = args;
    this.params = params;
    this.path = `/pets/${pathParameter.petId}`;
  }
}
