// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */
import { APIRequest, HTTPMethod } from "./types";
import { PetStore } from "./gen-ts";

export class listPets implements APIRequest<PetStore.pets.listPetsResponse> {
  response: PetStore.pets.listPetsResponse;
  method = HTTPMethod["get"];
  path: string;
  params: PetStore.pets.listPetsRequest;

  constructor(args: {
    params: PetStore.pets.listPetsRequest;
    pathParameter?: PetStore.pets.listPetsPathParameter;
  }) {
    const { params, pathParameter } = args;
    this.params = params;
    this.path = `/pets`;
  }
}

export class createPets
  implements APIRequest<PetStore.pets.createPetsResponse> {
  response: PetStore.pets.createPetsResponse;
  method = HTTPMethod["post"];
  path: string;
  params?: PetStore.pets.createPetsRequest;

  constructor(args: {
    params?: PetStore.pets.createPetsRequest;
    pathParameter?: PetStore.pets.createPetsPathParameter;
  }) {
    const { params, pathParameter } = args;
    this.params = params;
    this.path = `/pets`;
  }
}

export class showPetById
  implements APIRequest<PetStore.pets.showPetByIdResponse> {
  response: PetStore.pets.showPetByIdResponse;
  method = HTTPMethod["get"];
  path: string;
  params?: PetStore.pets.showPetByIdRequest;

  constructor(args: {
    params?: PetStore.pets.showPetByIdRequest;
    pathParameter: PetStore.pets.showPetByIdPathParameter;
  }) {
    const { params, pathParameter } = args;
    this.params = params;
    this.path = `/pets/${pathParameter.petId}`;
  }
}
