// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */
export type { default as Pet } from "./Pet";
export type { default as Pets } from "./Pets";
export type { default as Error } from "./Error";
