// THIS FILE IS GENERATED BY CODE GENERATOR. DO NOT CHANGE MANUALLY.
/* tslint:disable */
/* eslint-disable */

export default interface Pet {
  id: number;
  name: string;
  category?: 1 | 2 | 3;
  tag?: string;
  sex?: "male" | "female";
}
